# Simple Local Development Docker Compose
# Just the main application without optional services
version: '3.8'

services:
  nytex-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Core application settings
      - PYTHONPATH=/app
      - PORT=8080
      - ENVIRONMENT=development
      - DEBUG=True
      - RELOAD_TEMPLATES=True
      - LOG_LEVEL=DEBUG
      
    volumes:
      # Mount source code for development (hot reload)
      - ./app:/app/app
      - ./static:/app/static
      - ./templates:/app/templates
      - ./logs:/app/logs
      - ./scripts:/app/scripts
    env_file:
      - .env.local
    restart: unless-stopped
    command: uvicorn run:app --host 0.0.0.0 --port 8080 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: nytex-dashboard-network 