"""add_daily_weather_table_only

Revision ID: d9a8493aa014
Revises: 20250623_182639
Create Date: 2025-01-24 22:38:31.815072

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9a8493aa014'
down_revision = '20250623_182639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_weather',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_high', sa.Float(), nullable=True),
    sa.Column('temp_low', sa.Float(), nullable=True),
    sa.Column('temp_avg', sa.Float(), nullable=True),
    sa.Column('weather_main', sa.String(length=50), nullable=True),
    sa.Column('weather_description', sa.String(length=255), nullable=True),
    sa.Column('weather_icon', sa.String(length=10), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('wind_direction', sa.Integer(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_weather_date'), 'daily_weather', ['date'], unique=False)
    op.create_index(op.f('ix_daily_weather_location_id'), 'daily_weather', ['location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_weather_location_id'), table_name='daily_weather')
    op.drop_index(op.f('ix_daily_weather_date'), table_name='daily_weather')
    op.drop_table('daily_weather')
    # ### end Alembic commands ###
